version: "2.1"
services:
  postgres:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: parse
      POSTGRES_PASSWORD: YE3ndjb7XahKwSpk
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
